* Covid19 - links, activities, datasets
The global pandemy is forcing a lot of people to stay indoor. If you are one of
those people, or you would like to help battle this somehow, here are some of
the resources which can help you to contribute.

* Activities

- *Hack the Crisis* (https://www.hackcrisis.com/) Hackathon organised by Polish goverment, starts <2020-03-17 Tue> lasts to <2020-03-22 Sun>, with financial rewards $$ !

- *CORD-19 challenge* See kaggle dataset *CORD19*

- *Are you a researcher (of any kind)?* Crowd-fighting initiative to support
  COVID-19 researchers. Fill in the form, you might be useful.

* Datasets

*CORD19*
COVID-19 Open Research Dataset Challenge
https://www.kaggle.com/allen-institute-for-ai/CORD-19-research-challenge
Dataset, and challeng. Over 29,000 articles concerning COVID-19 and SARS-COV-2.
1000$ for each of tasks:
 - What is known about transmission, incubation, and environmental stability?
 - What do we know about COVID-19 risk factors?

*Covid19 chest xray*
https://github.com/ieee8023/covid-chestxray-dataset
growing dataset of images of chest x-rays

*WHO's database of COVID-19 related publications*
https://www.who.int/emergencies/diseases/novel-coronavirus-2019/global-research-on-novel-coronavirus-2019-ncov

* Statistics & Dashboards

*Our world in data statistics*
https://ourworldindata.org/coronavirus
Some useful statistics, e.g.,, per capita tests by country, confirmed COVID-19 cases by country

*Wikipedia statistics*
https://en.wikipedia.org/wiki/Template:2019%E2%80%9320_coronavirus_pandemic_data

*Daily reports data API*
https://github.com/GregVes/covid-19-api-server
API server that allows you to download daily reports
Here is an Javascript extractor https://github.com/GregVes/covid-19-data-extractor

*Tableau data hub for resources*
https://www.tableau.com/covid-19-coronavirus-data-resources
Access and analyze trusted COVID-19 (Coronavirus) global data

*John hopkins repository of data on kaggle*
https://www.kaggle.com/sudalairajkumar/novel-corona-virus-2019-dataset

*One of the earliest dashboards with a map*
https://www.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6

*Counter of deaths and infections with per country stats*
https://www.worldometers.info/coronavirus/

* Analyses & models

*Epidemic Calculator.*
http://gabgoh.github.io/COVID/index.html
Probably the moast advanced model of epidemic growth, availible as interactive graphic.
Gabriel Goh, 2020

*Pattern Classification For COVID-19 Growth Data*
https://towardsdatascience.com/classify-growth-patterns-for-covid-19-data-41af4c7adc55
Analysis of patterns of growths in multiple countries

*Computational predictions of protein structures associated with COVID-19*
https://deepmind.com/research/open-source/computational-predictions-of-protein-structures-associated-with-COVID-19
Deepmind's short text about applying AlphaFold towards discovering structure of
some of the proteins of the SARS-COV-2.

* Knowledge

*Coronavirus disease (COVID-19) advice for the public: Myth busters**
https://www.who.int/emergencies/diseases/novel-coronavirus-2019/advice-for-public/myth-busters
WHO's advice about COVID-19

*Coronavirus (COVID-19) Centers for Disease Control and Prevention, 2020.
[United States]*
https://www.cdc.gov/coronavirus/2019-nCoV/

*Nature: Coronavirus and the race to distribute reliable diagnostics*
https://www.nature.com/articles/d41587-020-00002-2
Natures article about coronavirus diagnostics

* Chats

- https://join-slack.pykonik.org/ --> #pydata channel. This is where this
  document is being born
- http://bit.ly/hackcrisiscom - slack channel for the hackcrisis hackathon
- https://join.slack.com/t/montrealai/shared_invite/zt-2vk74zhg-EHP1LDotKLWS0aPuhr4yZQ -
  montreal.ai group, there are some iniciatives comming from them

* Sources & other aggregators like this

- https://docs.google.com/spreadsheets/d/1VrCUWsoACAkjALHFl9B2CaVSTiMvp1sSn_b0zuud8Os/edit#gid=0 -
 created for hackcrisis
- http://montreal.ai/covid19.pdf?fbclid=IwAR2NSee7KcHdQozKgCF1BvvFlTktVR4c7QdonL6w0AZtt2Kgo_HvTmLREyo -
  coming from montreal.ai

* Miscellaneous

*TraceTogether**
https://www.tracetogether.gov.sg/
Community-driven contact tracing, via smartphone app. Government of Singapore.

* How to contribute to this document
- Use github issues pull requests, comments, issues etc
- you can edit either readme.org, or readme.md

