* Covid19 - links, activities, datasets
The global pandemy is forcing a lot of people to stay indoor. If you are one of
those people, or you would like to help battle this somehow, here are some of
the resources on how to contribute.

* Activities:

- *Hack the Crisis* (https://www.hackcrisis.com/) Hackathon organised by Polish goverment, starts <2020-03-17 Tue> lasts to <2020-03-22 Sun>, with financial rewards $$ !

- *CORD-19 challenge* See kaggle dataset *CORD19*

* Datasets:

*Daily reports data API*
https://github.com/GregVes/covid-19-api-server
API server that allows you to download daily reports
Here is an Javascript extractor https://github.com/GregVes/covid-19-data-extractor

*CORD19*
COVID-19 Open Research Dataset Challenge
https://www.kaggle.com/allen-institute-for-ai/CORD-19-research-challenge
Dataset, and challeng. Over 29,000 articles concerning COVID-19 and SARS-COV-2.
1000$ for each of tasks:
 - What is known about transmission, incubation, and environmental stability?
 - What do we know about COVID-19 risk factors?

*Covid19 chest xray*
https://github.com/ieee8023/covid-chestxray-dataset
growing dataset of images of chest x-rays

* Chats:
- https://join-slack.pykonik.org/ --> #pydata channel. This is where this
  document is being born
- http://bit.ly/hackcrisiscom - slack channel for the hackcrisis hackathon
- https://join.slack.com/t/montrealai/shared_invite/zt-2vk74zhg-EHP1LDotKLWS0aPuhr4yZQ -
  montreal.ai group, there are some iniciatives comming from them

* How to contribute to this document
- Use github issues pull requests, comments, issues etc
